### PR TITLE
remove lambdas and method references for 1.7 compat

### PR DESCRIPTION
**Pull request by mjnorman**
If you're interested.   Probable needs to be heavily tested. Relied on eclipse quick fix for most cases to remove lambdas and ref methods.

### CODE REVIEW

**Comment by nblumhardt** [comment]
Wow, those anonymous inner classes add a bit of verbosity :-)

I'm okay with this, if it makes the package more broadly useful. As far as I can tell, this should be fully compatible with our current version, correct?

@80dB any thoughts?

**Comment by mjnorman** [comment]
Might need to revisit the /lib path change I made.  I removed it playing around, but it might be needed on run.

**Comment by nblumhardt** [comment]
Thank you 👍

**Comment by Mart-Bogdan** [comment]
>Wow, those anonymous inner classes add a bit of verbosity :-)

Retrolambda can be used to still write with lambdas, but being able to use on older java

**Comment by mjnorman** [comment]
Yes I started using it yesterday.  It doesn't work for the method references that serilogj uses, so I had to end up rewriting those into Map.entry iterations.

**Comment by Mart-Bogdan** [comment]
@mjnorman indeed, it don't provide polyfill for missing default methods.

By the way, performancewise foreach would be more preferable, anyway.

**Comment by mjnorman** [comment]
@Mart-Bogdan could you elaborate on your comment for default methods and how that applies to the seqsink code below?

https://github.com/serilogj/serilogj/blob/e8ff5c3f72ce85b31c316ceadd52dc3b32924429/src/serilogj/sinks/seq/SeqSink.java#L119

**Comment by Mart-Bogdan** [comment]
@mjnorman 
forEach is **default** method in `Iterable`

```
    default void forEach(Consumer<? super T> action) {
        Objects.requireNonNull(action);
        for (T t : this) {
            action.accept(t);
        }
    }
```

As I recall there were lots of discussins on retrolambda thread regarding default methods and other stuff not available on previous JDKs, but I didn't tracked this issues.

I haven't used retrolambda for few years, as I stooped working with andriod and using Java8 on servers.

**Comment by Mart-Bogdan** [comment]
I think, yes, forEach and streams can be rewritten, but things like java-time should be maneged in other way

As I see:

`serilog-core`  without java time
`serilog-jdk6` with thre-ten backport 
`serilog-jdk8` with java-time api     

and later two packages would add writers dynamicaly, or something like that.

That's quite big refacroeing.


**P.S.** *descpaimer* I was using serilog on .Net. On java world I'm using JBoss type safe logging, so hust curios about serilogj, but not using it.

**Comment by Mart-Bogdan** [comment]
actually that could also be done by tricl of conditional class loading, which android using often
```
try{
Class.forName(".....");
//do stuff that use java time
} catch (ClassNotFoundException ...) {
...
}
```

parhaps store in static final boolean variable result of getting java time api

or use JDK version for probing

**Pull request closed without merging**
